heat_template_version: 2015-10-15

description: Single CentOS Instance template

parameter_groups:
  - label: CentOS Instance
    description: CentOS Instance settings
    parameters:
      - image_id
      - instance_type
      - key_name
  - label: Network Configuration
    description: CentOS Instance network ettings
    parameters:
      - network

parameters:
  key_name:
    type: string
    label: Key Name
    description: Name of key-pair to be used for Instance
    constraints:
      - custom_constraint: nova.keypair
  image_id:
    type: string
    label: Image ID
    description: CentOS Image to be used for Instance
    default: CentOS 7.2.1604
    constraints:
      - custom_constraint: glance.image
  instance_type:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used
    default: m1.small
    constraints:
      - custom_constraint: nova.flavor
  network:
    label: Network - eth0
    type: string
    description: Primary Network for the Instance
    constraints:
      - custom_constraint: neutron.network

resources:
  os_volume:
    type: OS::Cinder::Volume
    properties:
      size: 10
      image: { get_param: image_id }

  network_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: network }
      security_groups:
        - default

# Instances
  instance:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: instance_type }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: network_port }
      block_device_mapping_v2:
        - device_name: sda
          volume_id: { get_resource: os_volume }
          delete_on_termination: true

outputs:
  networks:
    description: Network block for the Instance
    value: { get_attr: [instance, networks] }

  instance_ip:
    description: The IP address of the Instance
    value: { get_attr: [instance, first_address] }
