heat_template_version: 2013-05-23
  
parameters:
  
  flavor:
    type: string
    description: Type of instance (flavor) to be used
    default: m1.small
  network_id:
    type: string
    description: ID of admin Neutron network into which servers get deployed
    default: 84c9c9b3-ed5b-45e0-8e97-b014a38e8545
  key_name:
    type: string
    description: Name of an existing key pair to use for the instance
    default: mbalas
  image:
    type: string
    default: 0b3162c4-60ab-4c10-b9f3-0484365ead57
     
resources:
  
  asg:
    type: OS::Heat::AutoScalingGroup
    properties:
      resource:
        type: OS::Nova::Server
        properties:
          key_name: { get_param: key_name }
          image: { get_param: image }
          flavor: { get_param: flavor }
          networks: [{network: {get_param: network_id} }]
          security_groups: [default, MBA_securityGroup]
          metadata: {"metering.stack": {get_param: "OS::stack_id"}}
      min_size: 1
      desired_capacity: 1
      max_size: 5
  
  scale_up_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: asg}
      cooldown: 60
      scaling_adjustment: 1
  
  scale_dn_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: asg}
      cooldown: 60
      scaling_adjustment: '-1'
  CPUAlarmHigh:
    type: OS::Ceilometer::Alarm
    properties:
      description: Scale-up if the average CPU > 50% for 10 minutes
      meter_name: cpu_util
      statistic: avg
      period: '600'
      evaluation_periods: '1'
      threshold: '50'
      alarm_actions: [{get_attr: [scale_up_policy, alarm_url]}]
      matching_metadata: {'metadata.user_metadata.stack': {get_param: "OS::stack_id"}}
      comparison_operator: gt
    
  CPUAlarmLow:
    type: OS::Ceilometer::Alarm
    properties:
      description: Scale-down if the average CPU < 15% for 10 minutes
      meter_name: cpu_util
      statistic: avg
      period: '600'
      evaluation_periods: '1'
      threshold: '15'
      alarm_actions: [{get_attr: [scale_dn_policy, alarm_url]}]
      matching_metadata: {'metadata.user_metadata.stack': {get_param: "OS::stack_id"}}
      comparison_operator: lt
